version: '3.8'

services:
  app:
    image: d-dimitrov-prod:${APP_IMAGE_TAG:-latest}
    container_name: d-dimitrov
    ports:
      - "3444:3000"
    env_file:
      - .env.production
    networks:
      - docker_network  # <--- ПРОМЯНА: Смени 'default' с името на твоята външна мрежа
    volumes:
      - /ssd/docker/share_upload_images:/app/upload
    restart: always

networks:
  docker_network: # Тази мрежа вече си я дефинирал правилно като външна
    external: true